### PR TITLE
Remove reference to non-publically abailable 3DR data

### LINKED ISSUE #93: git submodule update fails
```
git submodule update --init --recursive
Cloning into 'test/modules/dronekit-la-testdata-3dr'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'ssh://git@github.com/dronekit/dronekit-la-testdata-3dr' into submodule path 'test/modules/dronekit-la-testdata-3dr' failed
```

### PR DESCRIPTION
**Pull request by peterbarker**
This data is not publically available, and never will be.

Closes #93

### CODE REVIEW

**Comment by mrpollo** [comment]
Thanks @peterbarker

**Comment by peterbarker** [comment]
@mrpollo Note that I can't see why circleci is failing here; tells me something's not right.....

**Comment by mrpollo** [comment]
not sure why CircleCI isn't letting you in... I'll work on this you should have access

It's failing on not finding the submodule you just removed, my best guess is that theres still a reference to it somewhere

**Comment by mrpollo** [comment]
:dancer: thanks!

**Pull request merged**
