### PR TITLE
update circleci build script

### PR DESCRIPTION
**Pull request by mrpollo**
- use pre-configured gcc4.9
- remove jsoncpp dep

### CODE REVIEW

**Comment by mrpollo** [comment]
self merge!

**Comment by hamishwillee** [comment]
@peterbarker I guess there's one rule for the minions ....

**Comment by peterbarker** [comment]
And here I was, just about to do my Ramon-granted duty....

**Comment by mrpollo** [comment]
did I win anything for self merging?

**Comment by hamishwillee** [comment]
Yes, the "setting a bad example award" :-)

**Pull request merged**
