### PR TITLE
Cross-OS Platform support

### PR DESCRIPTION
**Pull request by mrpollo**
Support for OS X

### CODE REVIEW

**Comment by hamishwillee** [comment]
@mrpollo @peterbarker What are the build instructions/requirements?

**Comment by mrpollo** [comment]
just hit `make`!, I'm currently adding a OS X test environment on travis

**Comment by hamishwillee** [comment]
@mrpollo So if  you start with a vanilla OSX computer, everything you need for the dev environment is already present?

**Comment by mrpollo** [comment]
YES!!!!!

**Comment by mrpollo** [comment]
Great now this looks like it build and passed tests on both systems, we are good!

**Pull request merged**
